---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: peribolos-service-controller
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/open-services-group/peribolos-as-a-service:v0.0.1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
