---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - imagestream.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: development
    target:
      kind: DeploymentConfig
      name: peribolos-as-service
