---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run
spec:
  params:
    - name: REPO_NAME
      type: string
      default: ".github"
    - name: INSTALLATION_ID
      type: string
  steps:
    - name: apply-peribolos
      image: toolbox
      volumeMounts:
        - mountPath: /mnt/secret
          name: github-token
      env:
        - name: ORG_NAME
          valueFrom:
            secretKeyRef:
              name: peribolos-$(params.INSTALLATION_ID)
              key: orgName
      script: |
        #!/usr/bin/bash

        echo "Cloning repository..."
        # Clone repository
        git clone https://github.com/$ORG_NAME/$(params.REPO_NAME)
        cd $(params.REPO_NAME)

        # Run Peribolos on the repository
        echo "Running peribolos..."
        peribolos --config-path peribolos.yaml --github-token-path /mnt/secret/token --fix-org --fix-repos --fix-team-members --fix-teams --fix-team-repos --confirm
  volumes:
    - name: github-token
      secret:
        secretName: peribolos-$(params.INSTALLATION_ID)
        items:
          - key: token
            path: token
        optional: false
